= PHP-LRPM - PHP Long Running Process Manager

PHP-LRPM is a library for managing long running PHP processes.

== Motivation

Dynamic management of long running processes. Similar in function to process managers like daemontools or supervisord, but integrates with PHP code.

Can periodically reload configuration, e.g. from a database, and start/stop processes accordingly.

Currently not intended to be running as PID 1, nor was it tested in this role.

This https://youtu.be/MJkFHMOCEkg[talk by Giorgio Sironi] given at the Dutch PHP Conference in 2017 covers some of the problems and challenges when implementing long running PHP processes.

== Features

=== Simple

PHP-LRPM is built on top of POSIX process management facilities. PHP-LRPM starts its subprocesses via fork/exec and subprocesses don’t daemonize.

=== Efficient

The operating system signals PHP-LRPM immediately when a process terminates. PHP-LRPM will in turn attempt to restart the terminated process.

=== Flexible

PHP-LRPM uses exponential backoff when attempting to restart a process; some process managers will try several times in quick succession and fail the process until operator intervention.

== Usage

1. Implement the `ConfigurationSource`. This interface exposes a public method `loadConfiguration()`, that returns an associative array containing the configuration for all the workers.
2. Implement the `Worker`. This interface exposes two public methods, `start()` and `cycle()`. The child process will call `start()`, and then enter an endless loop, where it calls `cycle()`, and then checks for a shutdown condition (usually, the death of the LRPM supervisor process).

See `example.php` for a full running example with more details.

== Development

=== Roadmap / TODO list

==== Improve metadata handling

PHP-LRPM keeps metadata in an associative array. For efficient lookups by PID, a separate index is maintained.

This functionality could be offloaded to a generic library that wraps a hash map and maintains secondary indexes (similar to how secondary keys in an SQL database work).

==== Blocking shutdown

Wait for children after sending SIGTERM, follow up with SIGKILL if child doesn't respond to SIGTERM.

Implement blocking shutdown that waits for all children to exit.

== Some name ideas that were considered

* Palermo
* polearm
* poolroom

* pillar-pm
* polar-pm
* plural-pm
* plier-pm
